# Generated by Django 3.1 on 2020-08-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('last_name', models.CharField(max_length=60)),
                ('biography', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Journalist',
                'verbose_name_plural': 'Journalists',
            },
        ),
    ]
