# Generated by Django 3.1 on 2020-08-27 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='JobOffer',
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={'verbose_name': 'JobOffer', 'verbose_name_plural': 'JobOffers'},
        ),
    ]
